version: '3.9'
services:
  backend:
    container_name: bankcat-backend
    image: ${DOCKER_REGISTRY}/bankcat-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - 9000:9000
    expose:
      - 9000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 2048M
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first


  nginx:
    container_name: bankcat-nginx
    image: ${DOCKER_REGISTRY}/bankcat-nginx
    depends_on:
      - backend
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    deploy:
      replicas: 1
      x-aws-autoscaling:
        min: 1
        max: 5
        cpu: 80
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first


  mailhog:
    container_name: bankcat-mailhog
    image: mailhog/mailhog
    restart: unless-stopped
    tty: true
    ports:
      - 1025:1025
      - 8025:8025
    deploy:
      replicas: 1
      x-aws-autoscaling:
        min: 1
        max: 2
        cpu: 80
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
